# Generated by Django 5.2.8 on 2025-12-02 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee')]),
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emp_id', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')])),
                ('phone', models.IntegerField()),
                ('depertment', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales')])),
                ('designation', models.CharField()),
                ('salary', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
