# Generated by Django 5.2.9 on 2025-12-05 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employees_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idcord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField()),
                ('Blood_Group', models.CharField()),
                ('DOB', models.CharField()),
                ('Emergency_contact_No', models.CharField()),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
    ]
