# Generated by Django 5.2.9 on 2025-12-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_idcord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='email',
        ),
        migrations.AlterField(
            model_name='employees',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
