# Generated by Django 5.2.9 on 2025-12-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emp_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_attendance',
            name='total_hours',
            field=models.DurationField(default=0),
        ),
    ]
