# Generated by Django 5.2.9 on 2025-12-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_emp_attendance_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], null=True),
        ),
        migrations.AlterField(
            model_name='emp_attendance',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
