# Generated by Django 5.2.9 on 2025-12-12 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_emp_attendance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField()),
                ('year', models.IntegerField()),
                ('present_days', models.IntegerField()),
                ('salary', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
        ),
    ]
