# Generated by Django 5.2.9 on 2025-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_salary',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
