# Generated by Django 5.2.9 on 2026-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_emp_salary_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_attendance',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp_attendance',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp_attendance',
            name='lunch_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp_attendance',
            name='lunch_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10, null=True),
        ),
    ]
