# Generated by Django 5.2.9 on 2026-05-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_emp_attendance_break_end_emp_attendance_break_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_attendance',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='emp_attendance',
            name='break_start',
        ),
        migrations.RemoveField(
            model_name='emp_attendance',
            name='lunch_end',
        ),
        migrations.RemoveField(
            model_name='emp_attendance',
            name='lunch_start',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emp_salary',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_salary',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emp_salary',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='depertment',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idcord',
            name='Blood_Group',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='idcord',
            name='DOB',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='idcord',
            name='Emergency_contact_No',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='idcord',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
